apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe-deployment
  labels:
    app: tictactoe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
      - name: tictactoe
        image: opix/tictactoe:latest
        ports:
        - containerPort: 80
