apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe-deployment
  labels:
    app: tictactoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
      - name: tictactoe
        image: opix/tictactoe:latest
        env:
          - name: PORT
            value: "9292"
        ports:
        - containerPort: 9292
