version: '3.2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    environment:
      PORT: "9292"
      POSTGRES_HOST: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    depends_on:
      - "db"
