version: '3.0'
services:
  
      
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "9292:9292"
    
