version: '3.0'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "9292:9292"
    depends_on:
      - "db"
