<%= p ENV['RACK_ENV'] %>

default: &default
  adapter: postgresql
  encoding: unicode
  host:  <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: tictactoe
    
test:
  <<: *default
  database: tictactoe_test

production:
  <<: *default
  database: tictactoe_prod
