default: &default
  adapter: postgresql
  encoding: unicode
  host:  <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: tictactoe
    
test:
  <<: *default
  database: tictactoe_test

production:
  url: <%= URI.parse(ENV.fetch('DATABASE_URL', '')) %>
  encoding: 'unicode'
